# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mortgage_calculations}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Perry Hertler"]
  s.date = %q{2011-02-14}
  s.description = %q{Utilities for Mortgage related calculations (APR and Monthly Payments)}
  s.email = %q{perry@hertler.org}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
    "Gemfile",
    "Gemfile.lock",
    "Manifest",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/apr.feature",
    "features/step_definitions/apr_steps.rb",
    "features/support/env.rb",
    "lib/mortgage_calc.rb",
    "lib/mortgage_calc/mortgage_util.rb",
    "mortgage_calculations.gemspec",
    "spec/mortgage_calc/mortgage_util_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://www.pathf.com/blogs/2010/02/mortcalc-gem/}
  s.licenses = ["MORExchange"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Utilities for Mortgage related calculations (APR and Monthly Payments)}
  s.test_files = [
    "spec/mortgage_calc/mortgage_util_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

